# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

#!/usr/bin/env python3
"""Development-only self-signed certificate tool for the orchestration center.

Do not use certificates or private keys generated by this tool in production.
Production deployments must use certificates issued by a trusted public or
enterprise CA and follow the organization's certificate-management policy.

Usage:
    python -m generate_selfsign_cert <cert_dir> <cert_usage> [--dns HOST] [--ip ADDRESS] [--plain-key]
    python -m generate_selfsign_cert <cert_dir> serverAuth --issue-client <name>

    cert_dir:   Certificate directory path (e.g. etc/ssl)
    cert_usage: serverAuth (TLS communication) or dataSigning (data signing)

The password for the private key is entered interactively.
serverAuth defaults to localhost, 127.0.0.1 and ::1; explicit SAN options replace these defaults.

For serverAuth, deployment-ready files are produced alongside the raw ones:
    server.cer       TLS certificate (copy of server_RSA.cer)
    trust.cer        trust anchor (copy of server.cer)
    server_key.pem   encrypted private key (copy of server_key_RSA.pem)
    cert_pwd         key password without trailing newline

With --plain-key, server_key_nopass.pem (unencrypted key) is also written for
nginx and agent servers, which cannot decrypt the encrypted key themselves.
Protect it: it is written with owner-only permissions on Linux.

The self-signed server certificate doubles as its own CA (trust.cer), so with
verify_client=true client certificates can be issued from it:

    python -m generate_selfsign_cert <cert_dir> serverAuth --issue-client dev-proxy

writes <cert_dir>/<name>-client.cer / -client.key (unencrypted, owner-only on
Linux). The name "dev-proxy" is what the vite dev proxy picks up
automatically (etc/ssl/dev-proxy-client.cer / .key; restart vite after
issuing). The password is read from cert_pwd — no interaction needed.

The main backend reads the key password from etc/conf/cert_pwd by default
(ssl_keyfile_password in server.conf); copy cert_pwd there or point the
setting at cert_dir/cert_pwd.
"""

import argparse
import datetime
import os
import platform
import re
import shutil
import stat
import sys

from common.cert.certificate_generator import CertificateGenerator
from common.util.password_util import input_password_with_validation

SERVER_CER = "server.cer"
TRUST_CER = "trust.cer"
SERVER_KEY = "server_key.pem"
CERT_PWD = "cert_pwd"
PLAIN_KEY = "server_key_nopass.pem"
NAME_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9-]*")


def _owner_only(path: str) -> None:
    if platform.system().lower() == "linux":
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def _write_deploy_files(cert_dir: str, password: str, plain_key: bool) -> list[str]:
    """Copy the generated key material to the deployment file names.

    server.cer/trust.cer/server_key.pem/cert_pwd are the names the backend
    defaults to (conf_obj.DEFAULT_SSL_*); with plain_key an additional
    unencrypted server_key_nopass.pem is written for nginx and agent servers.
    """
    from cryptography.hazmat.primitives import serialization

    raw_cert = os.path.join(cert_dir, "server_RSA.cer")
    raw_key = os.path.join(cert_dir, "server_key_RSA.pem")
    server_cer = os.path.join(cert_dir, SERVER_CER)
    trust_cer = os.path.join(cert_dir, TRUST_CER)
    server_key = os.path.join(cert_dir, SERVER_KEY)

    shutil.copyfile(raw_cert, server_cer)
    shutil.copyfile(raw_cert, trust_cer)
    shutil.copyfile(raw_key, server_key)
    _owner_only(server_key)

    pwd_path = os.path.join(cert_dir, CERT_PWD)
    with open(pwd_path, "w", encoding="utf-8", newline="") as f:
        f.write(password)
    _owner_only(pwd_path)

    written = [server_cer, trust_cer, server_key, pwd_path]

    if plain_key:
        with open(raw_key, "rb") as f:
            key = serialization.load_pem_private_key(f.read(), password=password.encode("utf-8"))
        nopass_path = os.path.join(cert_dir, PLAIN_KEY)
        with open(nopass_path, "wb") as f:
            f.write(key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            ))
        _owner_only(nopass_path)
        written.append(nopass_path)
    return written


def issue_client_cert(cert_dir: str, name: str) -> tuple[str, str]:
    """Issue a TLS client certificate signed by the generated server certificate.

    Requires the server certificate material from a prior generation in
    cert_dir (server_RSA.cer, server_key_RSA.pem, cert_pwd). The client
    certificate chains to trust.cer, so the backend accepts it when
    verify_client=true.
    """
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

    raw_cert = os.path.join(cert_dir, "server_RSA.cer")
    raw_key = os.path.join(cert_dir, "server_key_RSA.pem")
    pwd_path = os.path.join(cert_dir, CERT_PWD)
    missing = [p for p in (raw_cert, raw_key, pwd_path) if not os.path.exists(p)]
    if missing:
        raise FileNotFoundError(
            "server certificate material missing: " + ", ".join(missing)
            + "; generate the server certificate first")

    with open(pwd_path, encoding="utf-8") as f:
        # strip(): tolerate hand-written password files with a trailing newline,
        # matching load_cert_password() semantics on the backend side.
        password = f.read().strip()
    with open(raw_cert, "rb") as f:
        ca_cert = x509.load_pem_x509_certificate(f.read())
    with open(raw_key, "rb") as f:
        ca_key = serialization.load_pem_private_key(f.read(), password=password.encode("utf-8"))

    client_key = rsa.generate_private_key(public_exponent=65537, key_size=3072)
    now = datetime.datetime.now(datetime.UTC)
    cert = (x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, name)]))
            .issuer_name(ca_cert.subject)
            .public_key(client_key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now)
            .not_valid_after(now + datetime.timedelta(days=3650))
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CLIENT_AUTH]), critical=False)
            .sign(ca_key, hashes.SHA256()))

    cert_path = os.path.join(cert_dir, f"{name}-client.cer")
    key_path = os.path.join(cert_dir, f"{name}-client.key")
    with open(cert_path, "wb") as f:
        f.write(cert.public_bytes(serialization.Encoding.PEM))
    with open(key_path, "wb") as f:
        f.write(client_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        ))
    _owner_only(key_path)
    return cert_path, key_path


def generate_self_signed_cert(cert_dir: str, cert_usage: str, password: str, *,
                              dns_names: list[str] | None = None,
                              ip_addresses: list[str] | None = None) -> bool:
    try:
        generator = CertificateGenerator(key_algorithm='RSA', dns_names=dns_names, ip_addresses=ip_addresses)
        success = generator.generate_self_signed_cert(cert_dir, cert_usage, password)

        if success:
            print(f"Successfully generated self-signed certificates in {cert_dir}")
            return True
        else:
            existing = [name for name in ("server_RSA.cer", "server_key_RSA.pem")
                        if os.path.exists(os.path.join(cert_dir, name))]
            if existing:
                print(f"Failed: certificate files already exist in {cert_dir}: "
                      f"{', '.join(existing)}")
                print("The tool refuses to overwrite. Remove them to regenerate"
                      " (regeneration issues a NEW key pair: re-issue client"
                      " certificates and redistribute trust material), or"
                      " generate into a different directory.")
            else:
                print("Failed to generate certificates (check the error output above)")
            return False
    except Exception as e:
        print(f"Error generating certificates: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("cert_dir", help="New certificate directory; existing files are not overwritten")
    parser.add_argument("cert_usage", choices=("serverAuth", "dataSigning"))
    parser.add_argument("--dns", action="append", help="DNS SAN; repeat for multiple hostnames")
    parser.add_argument("--ip", action="append", help="IP SAN; repeat for IPv4 or IPv6 addresses")
    parser.add_argument("--plain-key", action="store_true",
                        help="serverAuth only: also write the unencrypted server_key_nopass.pem "
                             "for nginx and agent servers")
    parser.add_argument("--issue-client", metavar="NAME",
                        help="serverAuth only: issue a TLS client certificate named NAME, signed "
                             "by the existing server certificate (requires cert_pwd); "
                             "\"dev-proxy\" is picked up by the vite dev proxy")
    args = parser.parse_args()
    if args.cert_usage == "dataSigning" and (args.dns or args.ip):
        parser.error("--dns and --ip apply only to serverAuth certificates")
    if args.cert_usage == "dataSigning" and args.plain_key:
        parser.error("--plain-key applies only to serverAuth certificates")
    if args.issue_client:
        if args.cert_usage != "serverAuth":
            parser.error("--issue-client issues a TLS client certificate; use serverAuth")
        if args.dns or args.ip or args.plain_key:
            parser.error("--issue-client issues a certificate from existing material; "
                         "it cannot be combined with --dns/--ip/--plain-key")
        if not NAME_PATTERN.fullmatch(args.issue_client):
            parser.error("client certificate name may contain letters, digits and dashes only")

        try:
            cert_path, key_path = issue_client_cert(args.cert_dir, args.issue_client)
        except Exception as e:
            print(f"Error issuing client certificate: {e}")
            sys.exit(1)
        print("Client certificate issued:")
        print(f"  {cert_path}")
        print(f"  {key_path}")
        if args.issue_client == "dev-proxy":
            print("The vite dev proxy reads these paths automatically; restart `npm run dev`.")
        print("For other clients (e.g. nginx upstream): configure proxy_ssl_certificate/"
              "proxy_ssl_certificate_key with this pair and proxy_ssl_trusted_certificate "
              "pointing at trust.cer.")
        sys.exit(0)

    password = input_password_with_validation("Enter private key password")
    if password != password.strip():
        parser.error("private key password must not start or end with whitespace")

    if not generate_self_signed_cert(args.cert_dir, args.cert_usage, password,
                                     dns_names=args.dns, ip_addresses=args.ip):
        sys.exit(1)

    if args.cert_usage == "serverAuth":
        try:
            written = _write_deploy_files(args.cert_dir, password, plain_key=args.plain_key)
        except Exception as e:
            print(f"Error writing deployment files: {e}")
            sys.exit(1)
        print("Deployment-ready files written:")
        for path in written:
            print(f"  {path}")
        print("Note: the backend reads the key password from etc/conf/cert_pwd by default; "
              f"copy {CERT_PWD} there or set ssl_keyfile_password in server.conf to "
              f"{args.cert_dir}/{CERT_PWD}.")
        if not args.plain_key:
            print("Note: nginx needs the unencrypted key; rerun with --plain-key or export it with "
                  "`openssl rsa -in server_key.pem -out server_key_nopass.pem -passin pass:<password>`.")
    sys.exit(0)


if __name__ == "__main__":
    main()
