// Copyright (c) 2026 Huawei Technologies Co., Ltd.
// All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0 (the "License"); you may
//    not use this file except in compliance with the License. You may obtain
//    a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
//    License for the specific language governing permissions and limitations
//    under the License.

/**
 * Plugin registry — auto-generated by the openan-plugin-discovery Vite plugin.
 *
 * Convention: any folder under plugins/ containing a plugin.manifest.js is
 * discovered automatically. Adding a plugin = drop the folder in. Removing
 * one for a delivery scenario = set "enabled": false in
 * plugins/plugin-overrides.json (plain JSON, no JS source touched).
 */
import pluginRegistry from 'virtual:openan-plugins';

export default pluginRegistry;
